
// // Question 1
// function isString(input) {
//     return typeof input === 'string';
    
// }
// console.log(isString('skander'));
// console.log(isString(911));
// console.log(isString('skan2000'));

// // // Question 2
// // function reverseString(str) {

// //     return str.split('').reverse().join(''); 

// // }
// // console.log(reverseString('skander'));
// // console.log(reverseString('911'));
// // console.log(reverseString('skan2000'));


// // Question 3
// function getLastElement(arr) {

//     return arr[arr.length - 1];}

// console.log(getLastElement([6, 7, 8]));     
// console.log(getLastElement(['S', 'K', 'A']));

// // Question 4
// function isUpperCase(str) {
    
//     return str === str.toUpperCase();
// }


// console.log(isUpperCase("SKANDER"));  
// console.log(isUpperCase("skander"));

// // Question 5
// function isUndefined(value) {

//     return value === undefined;
// }


// console.log(isUndefined(undefined));  
// console.log(isUndefined(911));       

// Question 6

function isEven(num) {

    return num % 2 === 0;
}


console.log(isEven(28));   
console.log(isEven(7)); 